[tool.black]
line-length = 88
target-version = ['py38']
exclude = '''
(
  /(
    | \.git          # root of the project
    | migrations/*
    |__pycache__
    |__pycache__/*
  )/
)
'''

[tool.isort]
profile = "black"
